a = Analysis(
    ['src\\app.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('assets\\icone.ico', 'assets'),
        ('assets\\arrow_down.svg', 'assets'),
        ('assets\\arrow_down_white.svg', 'assets'),
        ('assets\\check.svg', 'assets'),
        ('assets\\check_white.svg', 'assets'),
        ('assets\\canto_bandeja.PNG', 'assets'),
        ('src\\__init__.py', 'src'),
        ('src\\forms\\common\\help_content', 'forms/common/help_content'),
    ],
    hiddenimports=['PySide6.QtSvg'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Calculadora de Dobra',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets\\icone.ico',
    version='version_info.txt', # Adicionando o arquivo de versão (gerado dinamicamente)
)